export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const EVENT_LOADING = "EVENT_LOADING";
export const EVENT_LOADED = "EVENT_LOADED";
export const EVENT_ERROR = "EVENT_ERROR";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAIL = "UPDATE_FAIL";
export const EVENT_REGISTER_SUCCESS = "EVENT_REGISTER_SUCCESS";
export const EVENT_REGISTER_FAIL = "EVENT_REGISTER_FAIL";
export const SET_EVENT = "SET_EVENT";
export const CLEAR_EVENT = "CLEAR_EVENT";
export const CHECK_REGISTER = "CHECK_REGISTER";

// Loaders
export const LOADER_AUTH_USER = "LOADER_AUTH_USER";
export const LOADER_AUTH_LOGIN = "LOADER_AUTH_LOGIN";
export const LOADER_AUTH_REGISTER = "LOADER_AUTH_REGISTER";
export const LOADER_AUTH_LOGOUT = "LOADER_AUTH_LOGOUT";
export const LOADER_AUTH_UPDATE = "LOADER_AUTH_UPDATE";

// Events
export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAIL = "FETCH_EVENTS_FAIL";

// Event
export const FETCH_EVENT = "FETCH_EVENT";
export const FETCH_EVENT_SUCCESS = "FETCH_EVENT_SUCCESS";
export const FETCH_EVENT_FAIL = "FETCH_EVENT_FAIL";

// Event Category
export const FETCH_EVENT_CATEGORY = "FETCH_EVENT_CATEGORY";
export const FETCH_EVENT_CATEGORY_SUCCESS = "FETCH_EVENT_CATEGORY_SUCCESS";
export const FETCH_EVENT_CATEGORY_FAIL = "FETCH_EVENT_CATEGORY_FAIL";

// Event Type
export const FETCH_EVENT_TYPE = "FETCH_EVENT_TYPE";
export const FETCH_EVENT_TYPE_SUCCESS = "FETCH_EVENT_TYPE_SUCCESS";
export const FETCH_EVENT_TYPE_FAIL = "FETCH_EVENT_TYPE_FAIL";

// Clubs
export const FETCH_CLUBS = "FETCH_CLUBS";
export const FETCH_CLUBS_SUCCESS = "FETCH_CLUBS_SUCCESS";
export const FETCH_CLUBS_FAIL = "FETCH_CLUBS_FAIL";

// Sponsors
export const FETCH_SPONSORS = "FETCH_SPONSORS";
export const FETCH_SPONSORS_SUCCESS = "FETCH_SPONSORS_SUCCESS";
export const FETCH_SPONSORS_FAIL = "FETCH_SPONSORS_FAIL";

// Brochure
export const FETCH_BROCHURE = "FETCH_BROCHURE";
export const FETCH_BROCHURE_SUCCESS = "FETCH_BROCHURE_SUCCESS";
export const FETCH_BROCHURE_FAIL = "FETCH_BROCHURE_FAIL";